In [1]:
import pandas as pd
import json
import yaml
from pathlib import Path

In [2]:
MAIN_FOLDER = Path('..', 'outputs_000.002')
# MAIN_FOLDER = Path('..', 'outputs')

for f in MAIN_FOLDER.iterdir():
    if f.is_dir() :
        print(f.name)

032d5cccad8e2fcd096fb119ad5cdc26
b612cbe460d9db823577827ca483e673
b29b13c73213a24fb2aa7167fdfafb6b
ef5827318c41fae92ebfa1ebbf3d7043
97f1d9b8f556e750dea805b69ac7aaed
42246abe718a45163f6bbb45b2509269

In [3]:
folders = [f for f in MAIN_FOLDER.iterdir() if f.is_dir() and (Path(f, 'eval_results.json')).exists() ]

params = [ yaml.safe_load( Path(f, 'parameters.yaml').read_text() )
          for f in folders ]

results = list()
for f in folders:
    content = (Path(f, 'eval_results.json')).read_text()
    p = json.loads(content)
    p['_hash_id'] = f.name
    results.append(p)

In [4]:
df = pd.merge(
    pd.DataFrame(params),
    pd.DataFrame(results),
    on='_hash_id'
)

In [5]:
df

,_hash_id,_timestamp,batch_size,bf16,dataset,eval_steps,from_pretrained,generation_max_length,grad_steps,local_rank,...,student_weight,teachers_keys,teachers_weights,epoch,eval_accuracy,eval_loss,eval_runtime,eval_samples_per_second,eval_steps_per_second,eval_token_accuracy
0,032d5cccad8e2fcd096fb119ad5cdc26,2025-12-07T05:11:57.959040,8,False,piqa,250,google/flan-t5-large,65,8,-1,...,1.0,"[t5, llama]","[1.0, 1.0]",27.778164,0.697497,0.646115,875.4093,1.050,0.131,0.067537
1,b612cbe460d9db823577827ca483e673,2025-12-08T09:15:01.531844,8,False,riddle,250,google/flan-t5-large,65,8,-1,...,1.0,"[t5, llama]","[1.0, 1.0]",127.273349,0.658824,4.109076,516.5954,0.987,0.124,0.781471
2,b29b13c73213a24fb2aa7167fdfafb6b,2025-12-05T19:52:12.998636,8,False,arc,250,google/flan-t5-large,65,8,-1,...,1.0,"[t5, llama]","[1.0, 1.0]",388.914286,0.551073,4.556039,1248.7908,0.933,0.117,0.683969
3,ef5827318c41fae92ebfa1ebbf3d7043,2025-12-11T09:50:12.990520,8,False,pubmedqa,250,google/flan-t5-large,65,8,-1,...,1.0,"[t5, llama]","[1.0, 1.0]",875.000000,0.695000,6.903288,479.9520,0.833,0.104,0.850000
4,97f1d9b8f556e750dea805b69ac7aaed,2025-12-04T18:39:09.736796,8,False,obqa,250,google/flan-t5-large,65,8,-1,...,1.0,"[t5, llama]","[1.0, 1.0]",89.748387,0.706000,2.780930,489.2870,1.022,0.129,0.469545
5,42246abe718a45163f6bbb45b2509269,2025-12-09T10:26:03.781083,8,False,bioasq,250,google/flan-t5-large,65,8,-1,...,1.0,"[t5, llama]","[1.0, 1.0]",437.524590,0.894309,3.783119,147.1774,0.836,0.109,0.850000

In [6]:
df[
    ['_timestamp', 'dataset', 'epoch', 'batch_size', 'grad_steps', 'lr', 'eval_accuracy', 'eval_token_accuracy', 'eval_loss']
].sort_values('_timestamp')

,_timestamp,dataset,epoch,batch_size,grad_steps,lr,eval_accuracy,eval_token_accuracy,eval_loss
4,2025-12-04T18:39:09.736796,obqa,89.748387,8,8,0.0005,0.706000,0.469545,2.780930
2,2025-12-05T19:52:12.998636,arc,388.914286,8,8,0.0005,0.551073,0.683969,4.556039
0,2025-12-07T05:11:57.959040,piqa,27.778164,8,8,0.0005,0.697497,0.067537,0.646115
1,2025-12-08T09:15:01.531844,riddle,127.273349,8,8,0.0005,0.658824,0.781471,4.109076
5,2025-12-09T10:26:03.781083,bioasq,437.524590,8,8,0.0005,0.894309,0.850000,3.783119
3,2025-12-11T09:50:12.990520,pubmedqa,875.000000,8,8,0.0005,0.695000,0.850000,6.903288

In [7]:
# (df[
#     ['dataset', 'batch_size', 'grad_steps', 'lr', 'eval_accuracy']
# ].to_csv('experimento.csv', sep=',', index=False)
# )

In [8]:
md = (df[
    ['_timestamp', 'dataset', 'epoch', 'batch_size', 'grad_steps', 'lr', 'eval_accuracy', 'eval_token_accuracy', 'eval_loss']
].sort_values('_timestamp')
.to_markdown(index=False)
)

In [9]:
print(md)

| _timestamp                 | dataset   |    epoch |   batch_size |   grad_steps |     lr |   eval_accuracy |   eval_token_accuracy |   eval_loss |
|:---------------------------|:----------|---------:|-------------:|-------------:|-------:|----------------:|----------------------:|------------:|
| 2025-12-04T18:39:09.736796 | obqa      |  89.7484 |            8 |            8 | 0.0005 |        0.706    |             0.469545  |    2.78093  |
| 2025-12-05T19:52:12.998636 | arc       | 388.914  |            8 |            8 | 0.0005 |        0.551073 |             0.683969  |    4.55604  |
| 2025-12-07T05:11:57.959040 | piqa      |  27.7782 |            8 |            8 | 0.0005 |        0.697497 |             0.0675372 |    0.646115 |
| 2025-12-08T09:15:01.531844 | riddle    | 127.273  |            8 |            8 | 0.0005 |        0.658824 |             0.781471  |    4.10908  |
| 2025-12-09T10:26:03.781083 | bioasq    | 437.525  |            8 |            8 | 0.0005 |        0.894309 |             0.85      |    3.78312  |
| 2025-12-11T09:50:12.990520 | pubmedqa  | 875      |            8 |            8 | 0.0005 |        0.695    |             0.85      |    6.90329  |

## Tempo de treinamento

In [10]:
folders = [f for f in MAIN_FOLDER.iterdir() if f.is_dir() and (Path(f, 'train_results.json')).exists() ]

results = list()
for f in folders:
    content = (Path(f, 'train_results.json')).read_text()
    p = json.loads(content)
    p['_hash_id'] = f.name
    results.append(p)


df_train = pd.merge(
                pd.json_normalize(results,record_prefix='metrics'),
                df[['_hash_id', 'dataset', '_timestamp']],
                on='_hash_id'
            )

df_train.columns = df_train.columns.str.replace('metrics.', '', regex=False)
df_train['train_runtime_hours'] = df_train['train_runtime'] / 3600

md = (
    df_train[
        ['_timestamp', 'dataset', 'train_runtime_hours']
    ].sort_values('_timestamp')
    .to_markdown(index=False)
)

df_train[
    ['_timestamp', 'dataset', 'train_runtime_hours']
].sort_values('_timestamp')

                   _timestamp   dataset  train_runtime_hours
4  2025-12-04T18:39:09.736796      obqa            25.074605
2  2025-12-05T19:52:12.998636       arc            32.977168
0  2025-12-07T05:11:57.959040      piqa            27.797326
1  2025-12-08T09:15:01.531844    riddle            25.034566
5  2025-12-09T10:26:03.781083    bioasq            47.354293
3  2025-12-11T09:50:12.990520  pubmedqa            52.825915

In [11]:
print(md)

| _timestamp                 | dataset   |   train_runtime_hours |
|:---------------------------|:----------|----------------------:|
| 2025-12-04T18:39:09.736796 | obqa      |               25.0746 |
| 2025-12-05T19:52:12.998636 | arc       |               32.9772 |
| 2025-12-07T05:11:57.959040 | piqa      |               27.7973 |
| 2025-12-08T09:15:01.531844 | riddle    |               25.0346 |
| 2025-12-09T10:26:03.781083 | bioasq    |               47.3543 |
| 2025-12-11T09:50:12.990520 | pubmedqa  |               52.8259 |